---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

install:
  - yarn install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - yarn try $EMBER_TRY_SCENARIO --skip-cleanup

jobs:
  fail_fast: true

  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    - stage: Locked Dependencies
      name: Lint
      script: yarn lint:js
    - name: Tests
      script: yarn test:ember
    - name: Node Tests
      script: yarn test:node

    - stage: Floating Dependencies
      name: Tests
      script: yarn test:ember
      env: EMBER_TRY_SCENARIO=ember-default
    - name: Node Tests
      install: yarn install --no-lockfile --non-interactive
      script: yarn test:node

    - stage: Scenarios
      env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic
